# Generated by Django 5.0.1 on 2024-01-29 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_schedule_date_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
