# Generated by Django 5.0.1 on 2024-01-29 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_schedule_employee_remove_shift_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='client',
        ),
        migrations.AddField(
            model_name='shift',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
