# Generated by Django 5.0.1 on 2024-01-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_schedule_end_date_alter_schedule_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
    ]
