# Generated by Django 5.0.1 on 2024-01-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_schedule_client_alter_schedule_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
