# Generated by Django 5.0.1 on 2024-01-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_shift_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='client',
        ),
    ]
