# Generated by Django 5.0.1 on 2024-01-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_schedule_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
    ]
